app = "karttamaster-web"
primary_region = "arn"

[build]
  [build.args]
    VITE_MML_API_KEY = "5f97e61e-6f63-40d5-8d15-53b79055f66d"

[env]
  PORT = "3001"
  DB_PATH = "/data/karttamaster.db"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  auto_stop_timeout = "5m"

  [[http_service.checks]]
    method = "GET"
    path = "/api/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"

[[mounts]]
  source = "karttamaster_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
